//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotTowelExample
{
    using System;
    using System.Collections.Generic;
    
    public class TaskSet
    {
        public TaskSet()
        {
            this.IsDone = false;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsDone { get; set; }
    }
}
